### ISSUE TITLE
Listen to subset of a state

### ISSUE THREAD

**Issue by agenthunt** [frostymarvelous/Fluxxan#6]
Firstly, awesome library. Congrats!!!

I was wondering how would it be possible to listen to subset of a state or filter the state that the UI can listen to ? At present, any state changes are now propagated to all the UI.

**Comment by thedumbtechguy** [comment]
@agenthunt You can override the `hasStateChanged(State newState, State oldState);` method on the `StateListener`.
You keep some sort of reference (it could be a hashcode or an ID or the actual) to the actual subset in the listener and check if the new subset has changed or if you use immutables, I believe you can do something along the lines of

```
hasStateChanged(State newState, State oldState) {
    newState.subset != oldState.subset;
}
```

This will prevent `onStateChanged` from being called. 
There is currently no way to specify that a listener only listen to specific changes and I am uncertain if I will be implementing that as it will unduly complicate the library.

Also, I am glad at least one other person is attempting to use this.

**Comment by agenthunt** [comment]
Thanks @frostymarvelous . Deciding the subset seems more cumbersome. I guess I didn't wanted the subset ,  I wanted the complete diff of what was changed so that I could update the UI.  I ended up receiving all changes in onStateChanged and decide which has changed and update the UI.  I guess the missing piece to use a virtual dom kind of library to make fully reactish.

**Comment by thedumbtechguy** [comment]
@agenthunt I've actually been wondering how to implement something similar to the virtual DOM.
It's turning out to be more difficult than I can imagine.

**Comment by agenthunt** [comment]
There seems to be one https://github.com/zserge/anvil but haven't tried it myself yet. 
 If it was possibility to extract virtual dom bits from react-native. That would be a quite complex as well.

**Comment by thedumbtechguy** [comment]
I've seen anvil. Looks to verbose for my liking however. 
You do have a point with react native. I'll look into it.
