### ISSUE TITLE
How to handle different states for different screens

### ISSUE THREAD

**Issue by mmangliers** [frostymarvelous/Fluxxan#7]
From what I can tell, the library relies on having on universal application state. How does the library handle having 'sub-states' for different fragments and views to compartmentalize the logic and data storage?

**Comment by thedumbtechguy** [comment]
So, this design comes from flux itself.

What I do is, have a single immutable AppState object which doesn't
actually hold any state.
Then on this object, I have immutable nodes which represent different states of the app.

I also group my reducers based on which node they reduce.

Eg. (this is rudimentary as I am on mobile but I hope you get the idea)
AppState
- ArtistsState
- CurrentArtistState
- AlbumsState
- CurrentAlbumState

Then I have ArtistsReducer, AlbumsReducer etc.

How you group them pretty much depends on the kind of app and the data.

**Comment by mmangliers** [comment]
Cool, that's pretty close to what I had in mind; just wanted to make sure I wasn't going down a crazy road. Thanks! Looking forward to toying with this library

**Comment by thedumbtechguy** [comment]
Just make sure each node is immutable and never listen to the root state in `hasStateChanged`,  as any changes to any node will change the root itself. 
Treat the root as a simple holder.

**Comment by mmangliers** [comment]
Similar question; to use the Fluxxan coordinator, do we need to have a single action creator? I want to use different creators in different fragments, but I need to implement getFlux(). Fluxxan itself is created with only one action creator, and as far as I see we don't want more than one instance of Fluxxan because it's tied to the dispatcher.

**Comment by thedumbtechguy** [comment]
No you don't.
You don't even need an action creator.

You can use the alternative constructor `public Fluxxan(@NonNull State state)` and implement your creators as standalone Singletons.

But this is from my app.

```
public class AppActions extends BaseActionCreator {
    final private ActionCreator[] mActions ;
    final public AuthActions Auth = new AuthActions();
    final public ArtistActions Artists = new ArtistActions();
    final public SongActions Songs = new SongActions();
    final public PlayerActions Player = new PlayerActions();
    final public AlbumActions Albums = new AlbumActions();
    final public GenreActions Genres = new GenreActions();
    final public OfflineActions Offline = new OfflineActions();
    final public UserActions User = new UserActions();
    final public MainActions Main = new MainActions();

    public AppActions() {
        mActions = new ActionCreator[]{
                Auth,
                Artists,
                Songs,
                Player,
                Albums,
                Genres,
                Offline,
                User,
                Main
        };
    }

    @Override
    public void setDispatcher(Dispatcher dispatcher) {
        super.setDispatcher(dispatcher);

        //set dispatcher for all children
        for(int i = 0; i < mActions.length; i++)
            mActions[i].setDispatcher(dispatcher);
    }
}
```

**Comment by thedumbtechguy** [comment]
This is a design I am really open to suggestions for.

**Comment by mmangliers** [comment]
I realized that just after I posted. I think the part of the design that bugs me a little is that the listener Fragment/Activity/View classes require a type for the action creator just so they can retrieve Fluxxan, which seems a little odd considering the action creator is optional in the first place. Easy enough to get around by just giving it the base interface though, if that's what you want to do.

Right now I'm debating whether to have all my action creators gathered like you have above, or to just create them on the scope that they're needed. Right now I'm playing with a slightly tweaked StateListenerFragment that creates the action creator it needs in OnStart and hooks it into the dispatcher from getFlux. I'm also not providing the default implementation of hasStateChanged for this abstract listener as I'll never be checking against the global state, only nodes. I can't see any reason action creators can't be scoped to the fragment, so I think I'll play with this for a bit.

**Comment by thedumbtechguy** [comment]
Nice catch.

Since I am by default providing a creator, I didn't realize the design flaw.
I'll look at it again try to come up with a good fix.

**Comment by mmangliers** [comment]
Off the top of my head, there are two things I would try to allow for multiple action creators to avoid a single 'god-creator' so to speak:
1. Make every action creator class require some sort of static tag (or just use the class.name) and allow registering multiple action creators in Fluxxan with a map tag->ac. Then provide a getter that lets us retrieve a specific creator with the tag. Downside is the user is responsible for casting the return value from a generic ActionCreator to whatever they need.
2. When registering an action creator with Fluxxan, have Fluxxan inspect the creation methods somehow so that it can act as an entry point for all action creation. Once we give a creator to Fluxxan, we needn't deal directly with it again. When you tell Fluxxan to create an action, it searches its internal map for the creator to forward the call to. I'm not a big fan of this idea, as it makes Fluxxan do more than I feel it should and it's fairly messy (also probably slower).

Either way, both of these allow us to instantiate Fluxxan without needing to provide it a specifc creator type. Heck, even just removing that requirement in the first place would work - you'd just have to cast the ActionCreator to your implementation on retrieval. That said, not sure if any of these are particularly appealing to the implementation you're aiming for.

**Comment by thedumbtechguy** [comment]
I'm leaning more towards "Heck, even just removing that requirement in the first place would work".
There is no reason to have the creator in Fluxxan. This is a remnant from the design of Fluxxor which due to it being a simple js object, made sense.

**Comment by mmangliers** [comment]
Works for me. The only reason to have it in there is convenience, and I'm not fully convinced it's worth it or needed

**Comment by thedumbtechguy** [comment]
Exactly.

**Comment by thedumbtechguy** [comment]
I've pushed a new release with the required changes.
